### ISSUE TITLE
Style and Responsiveness

### ISSUE THREAD

**Issue by stephaneeh** [caoimhejyoti/out-and-about#114]
- [x] navbar (flex correct, small menu option)
- [x] update landing page (many things)
- [x] fix badge container (badges to stay in container, flex correctly)
- [x] fix map container (make sure its centred, flex correctly, responds under badges)
- [x] update profile pages (text field updates, universal styled buttons)
- [x] update QR code results page (centre content)

**Comment by stephaneeh** [comment]
Match styling universally

**Comment by stephaneeh** [comment]
WHAT I DID for update landing page (many things)

- updated background
- updated hero
- add flex grid
- add signup to landing page
- updated content on page

**Comment by caoimhejyoti** [comment]
updated profile page buttons to match styling. 

#124 
#125

**Comment by caoimhejyoti** [comment]
Qr code styling = #126

**Comment by caoimhejyoti** [comment]
#137
