### ISSUE TITLE
create seed information

### ISSUE THREAD

**Issue by caoimhejyoti** [caoimhejyoti/out-and-about#31]
data to seed

- [x] user
- [x] quests
- [x] location
- [x] riddles
- [x] badges
- [x] tiers
- [x] qrcodes

**Comment by caoimhejyoti** [comment]
seed date created for all but quest. need support in confirming how to use id from chosen quests etc.

**Comment by caoimhejyoti** [comment]
are we able to add seed data via compass?

**Comment by stephaneeh** [comment]
Yeah we should be able to - it would work very similar to insomnia, in that you just need to write the insomnia and then just add a query to add the data

**Comment by caoimhejyoti** [comment]
All data seeded and talking to each other!
